language: node_js
node_js:
  - 12
script:
  - mkdir report/
  - mvn test -B 2>&1 | tee report/javaReport.txt; test ${PIPESTATUS[0]} -eq 0
  - cd react/
  - npm install
  - CI=false npm run test 2>&1 | tee ../report/nodeReport.txt; test ${PIPESTATUS[0]} -eq 0

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAGES  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: report/
  target_branch: travisCI-reports
  on:
    branch: master